### ISSUE TITLE
rTorrent Suggestion: Display Newest Torrent

### ISSUE THREAD

**Issue by keldian** [Cloudbox/cloudbox_motd#12]
Going out on a limb that I'm not the only one who'd find this useful.
```yaml
Torrents............: Total: 484 | Downloading: 0 | Uploading: 0
Torrents Rx/Tx......: Down: 1 Kbps | Up: 2 Kbps
Torrents Bandwidth..: Downloaded: 310.47 GB | Uploaded: 769.66 GB
Newest Torrent......: Le.Torrent.2012.1080p.BluRay.x264.DD.5.1-CoolGrp | 5.11 GiB
```
